### ISSUE TITLE
Don't play around with dataframe

### ISSUE THREAD

**Issue by bmschmidt** [llimllib/nbastats#1]
Hi there, I was just poking around to see how you implemented duckdb bundling from your link on their page. Super helpful, thanks!

I noticed that you've got a note in your code to 'play around with dataframe' in arrow-js. So I wanted to give you a heads up that the maintainers have said on the arrow mailing list that they're actually planning on removing the dataframe classes from arrow-js, so don't waste your time!

**Comment by llimllib** [comment]
Hah, thanks! that's super helpful, cheers

**Comment by llimllib** [comment]
(to be clear because this is the internet and everything reads sarcastic to me: that was not sarcastic, that's really useful)
